"""Change images_json column type to JSON

Revision ID: 4462b357ec75
Revises: bdf2b46889b4
Create Date: 2025-11-28 18:42:09.926665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4462b357ec75'
down_revision: Union[str, Sequence[str], None] = 'bdf2b46889b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'images_json',
               existing_type=mysql.TEXT(),
               type_=mysql.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'images_json',
               existing_type=mysql.JSON(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
