"""Update product JSON columns data type

Revision ID: bdf2b46889b4
Revises: 
Create Date: 2025-11-28 18:21:01.140206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bdf2b46889b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_desserts_id'), table_name='desserts')
    op.drop_index(op.f('ix_desserts_name'), table_name='desserts')
    op.drop_table('desserts')
    op.alter_column('products', 'sizes_json',
               existing_type=mysql.VARCHAR(length=1000),
               type_=mysql.JSON(),
               existing_nullable=True)
    op.alter_column('products', 'toppings_json',
               existing_type=mysql.VARCHAR(length=1000),
               type_=mysql.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'toppings_json',
               existing_type=mysql.JSON(),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('products', 'sizes_json',
               existing_type=mysql.JSON(),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)
    op.create_table('desserts',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('price', mysql.FLOAT(), nullable=False),
    sa.Column('is_vegan', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('image_url', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_desserts_name'), 'desserts', ['name'], unique=False)
    op.create_index(op.f('ix_desserts_id'), 'desserts', ['id'], unique=False)
    # ### end Alembic commands ###
